{
 "title": "Combined Stats",
 "description": "Empower statistics of slices, lvaps, and algorithms",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LVAP's best MCS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "MCS" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  best_mcs_prob\nFROM lvap_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "TX throughput per LVAP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  tx_throughput_mbps\nFROM bin_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "TX packets per second per LVAP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  tx_packets_per_second\nFROM bin_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "RX throughput per LVAP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  rx_throughput_mbps\nFROM bin_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "RX packets per second per LVAP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  rx_packets_per_second\nFROM bin_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP1 - STA's association",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Number of associated STAs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  flag\nFROM lvap_association_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr = '00:0D:B9:42:6A:00'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP2 - STA's association",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Number of associated STAs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  flag\nFROM lvap_association_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr = '00:0D:B9:42:72:08'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP3 - STA's association",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Number of associated STAs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  flag\nFROM lvap_association_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr = '00:0D:B9:53:E0:4C'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP1 - Slices' Throughput -Channel 1",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Mbits", "label": "Throughput (Mbps)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  throughput_mbps\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:6A:00'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP2 - Slices' Throughput - Channel 6",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "Mbits", "label": "Throughput (Mbps)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  throughput_mbps\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:72:08'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP3 - Slices' Throughput - Channel 11",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "Mbits", "label": "Throughput (Mbps)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  throughput_mbps\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:53:E0:4C'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP1 - Slices' Queue Delay",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms", "label": "Queue Delay (ms)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  queue_delay_msec\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:6A:00'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP2 - Slices' Queue Delay",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "ms", "label": "Queue Delay (ms)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  queue_delay_msec\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:72:08'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP3 - Slices' Queue Delay",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "ms", "label": "Queue Delay (ms)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  queue_delay_msec\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:53:E0:4C'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP1 - Slices' Current Quantum",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  current_quantum\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:6A:00'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP2 - Slices' Current Quantum",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  current_quantum\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:72:08'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP3 - Slices' Current Quantum",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  current_quantum\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:53:E0:4C'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP1 - Slices' Deficit",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "µs", "label": "Deficit AVG" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  deficit,\n  deficit_avg,\n  deficit_used\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:6A:00'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP2 - Slices' Deficit",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "µs", "label": "Deficit AVG" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  deficit,\n  deficit_avg,\n  deficit_used\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:72:08'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP3 - Slices' Deficit",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "µs", "label": "Deficit AVG" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  deficit,\n  deficit_avg,\n  deficit_used\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:53:E0:4C'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTPs - channel occupancy",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "Mbits", "label": "Throughput (Mbps)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  wtp_addr AS metric,\n  channel_utilization\nFROM wifi_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Algorithms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Slicing Parameters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short", "label": "Parameter value" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  min_quantum,\n  max_quantum,\n  inc_rate,\n  dec_rate,\n  up_bw_threshold_mbps\nFROM adaptive_slicing\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Shaping Parameters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 71 },
   "yaxes": [
    { "format": "short", "label": "Parameter value" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  min_bw_mbps,\n  max_bw_mbps,\n  dec_rate,\n  inc_rate,\n  up_bw_threshold_mbps\nFROM adaptive_shaping\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Weights QoS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  type AS metric,\n  wtp_channel_load_rate,\n  sta_association_flag,\n  wtp_load_expected_mbps,\n  wtp_load_measured_mbps,\n  wtp_queue_delay_ms,\n  wtp_sta_rssi_dbm\nFROM mcda_weights\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  type LIKE 'QoS'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Weights BE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  type AS metric,\n  wtp_channel_load_rate,\n  sta_association_flag,\n  wtp_load_expected_mbps,\n  wtp_load_measured_mbps,\n  wtp_queue_delay_ms,\n  wtp_sta_rssi_dbm\nFROM mcda_weights\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  type LIKE 'BE'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP1 - MCDA Closeness/Rank",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  closeness,\n  rank\nFROM mcda_results\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:6A:00'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP2 - MCDA Closeness/Rank",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  closeness,\n  rank\nFROM mcda_results\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:72:08'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP3 - MCDA Closeness/Rank",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  closeness,\n  rank\nFROM mcda_results\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:53:E0:4C'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP1 - MCDA STA's association",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short", "label": "Number of associated STAs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  association_flag\nFROM mcda_association_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:6A:00'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP2 - MCDA STA's association",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 90 },
   "yaxes": [
    { "format": "short", "label": "Number of associated STAs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  association_flag\nFROM mcda_association_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:72:08'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP3 - MCDA STA's association",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 90 },
   "yaxes": [
    { "format": "short", "label": "Number of associated STAs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  association_flag\nFROM mcda_association_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:53:E0:4C'\nORDER BY 1,2"
    }
   ]
  }
 ]
}