{
 "title": "LVAP Stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "LVAP's best MCS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "MCS" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  best_mcs_prob\nFROM lvap_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "TX throughput per LVAP",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  tx_throughput_mbps\nFROM bin_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "RX throughput per LVAP",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  rx_throughput_mbps\nFROM bin_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "TX packets per second per LVAP",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  tx_packets_per_second\nFROM bin_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "RX packets per second per LVAP",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  rx_packets_per_second\nFROM bin_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1,2"
    }
   ]
  }
 ]
}