{
 "title": "NCQM Stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "NCQM last packets",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  unknown_ap_addr AS metric,\n  last_packets\nFROM ncqm_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "NCQM history of packets",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  unknown_ap_addr AS metric,\n  hist_packets\nFROM ncqm_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "NCQM average RSSI",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  unknown_ap_addr AS metric,\n  last_rssi_avg\nFROM ncqm_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "NCQM moving RSSI",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  unknown_ap_addr AS metric,\n  mov_rssi\nFROM ncqm_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1,2"
    }
   ]
  }
 ]
}