{
 "title": "Slice Stats",
 "description": "Empower slice statistics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "WTP1 - STA's association",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number of associated STAs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  flag\nFROM lvap_association_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr = '00:0D:B9:42:6A:00'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP2 - STA's association",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number of associated STAs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  flag\nFROM lvap_association_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr = '00:0D:B9:42:72:08'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP3 - STA's association",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number of associated STAs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  lvap_addr AS metric,\n  flag\nFROM lvap_association_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr = '00:0D:B9:53:E0:4C'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP1 - Slices' Throughput -Channel 1",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Mbits", "label": "Throughput (Mbps)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  throughput_mbps\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:6A:00'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP2 - Slices' Throughput - Channel 6",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "Mbits", "label": "Throughput (Mbps)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  throughput_mbps\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:72:08'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP3 - Slices' Throughput - Channel 11",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "Mbits", "label": "Throughput (Mbps)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  throughput_mbps\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:53:E0:4C'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP1 - Slices' Queue Delay",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms", "label": "Queue Delay (ms)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  queue_delay_msec\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:6A:00'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP2 - Slices' Queue Delay",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "ms", "label": "Queue Delay (ms)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  queue_delay_msec\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:72:08'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP3 - Slices' Queue Delay",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "ms", "label": "Queue Delay (ms)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  queue_delay_msec\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:53:E0:4C'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP1 - Slices' Current Quantum",
   "type": "graph",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  current_quantum\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:6A:00'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP2 - Slices' Current Quantum",
   "type": "graph",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  current_quantum\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:72:08'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP3 - Slices' Current Quantum",
   "type": "graph",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  current_quantum\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:53:E0:4C'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP1 - Slices' Average Deficit Used",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "µs", "label": "Deficit AVG" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  deficit_avg\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:6A:00'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP2 - Slices' Average Deficit Used",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "µs", "label": "Deficit AVG" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  deficit_avg\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:42:72:08'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WTP3 - Slices' Average Deficit Used",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "µs", "label": "Deficit AVG" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  dscp AS metric,\n  deficit_avg\nFROM slice_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms) AND\n  wtp_addr LIKE '00:0D:B9:53:E0:4C'\nORDER BY 1,2"
    }
   ]
  }
 ]
}