{
 "title": "UCQM Stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "UCQM history of packets",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  wtp_sta AS metric,\n  hist_packets\nFROM ucqm_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "UCQM last packets",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  wtp_sta AS metric,\n  last_packets\nFROM ucqm_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "UCQM average RSSI",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  wtp_sta AS metric,\n  last_rssi_avg\nFROM ucqm_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "UCQM moving RSSI",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_ms AS \"time\",\n  wtp_sta AS metric,\n  mov_rssi\nFROM ucqm_stats\nWHERE\n  $__unixEpochFilter(timestamp_ms)\nORDER BY 1,2"
    }
   ]
  }
 ]
}